name: automerge
on:
  pull_request_target:
    types:
      - synchronize
      - opened
      - edited
      - reopened
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: no-actions
        name: no automerge for GitHub actions changes
        run: |
          if git diff --exit-code origin/main .github; then
            exit 1
          fi
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "!nomerge"


