name: automerge
on:
  pull_request_target:
    types:
      - synchronize
      - opened
      - edited
      - reopened
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - id: validate-schemas
        name: validate schemas
        run: ./scripts/validate-schemas.sh


